### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tns

### Importing the datasets

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X1 = data.iloc[:,3:-1].values
y1 = data.iloc[:,-1:].values

### Data Preprocessing

In [4]:
### Encoding the categorical values
### In our dataset Geography is the categorical data- France,Spain,Germany
data.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encode",OneHotEncoder(),[1])],remainder='passthrough')
X1 = np.array(ct.fit_transform(X1))

In [6]:
### Encoded Data
X1

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
### LabelEncoding the Gender column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X1[:,4] = le.fit_transform(X1[:,4])
X1[:,4]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [9]:
### Splitting the data into test and training set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X1,y1,test_size=0.2,random_state=2)
X_train[:]

array([[1.0, 0.0, 0.0, ..., 1, 1, 64716.08],
       [0.0, 1.0, 0.0, ..., 1, 1, 131886.46],
       [1.0, 0.0, 0.0, ..., 1, 1, 99661.46],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 195033.07],
       [0.0, 1.0, 0.0, ..., 1, 0, 176680.16],
       [1.0, 0.0, 0.0, ..., 1, 0, 151316.37]], dtype=object)

In [10]:
### Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train,X_test = scaler.fit_transform(X_train),scaler.transform(X_test)

### Building an ANN-(ARTIFICIAL NEURAL NETWORK)

1. Initializing the ANN

In [11]:
ann = tns.keras.models.Sequential()

2. Adding the 1st Hidden Layer

In [12]:
ann.add(tns.keras.layers.Dense(units = 6, activation = 'relu'))

3. Adding the 2nd Hidden Layer

In [13]:
ann.add(tns.keras.layers.Dense(units = 6, activation = 'relu'))

4. Adding the output Layer

In [14]:
ann.add(tns.keras.layers.Dense(units = 1, activation = 'sigmoid'))

### Training the ANN model

1. Compiling the ANN

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

2. Training the ANN on training set

In [16]:
ann.fit(X_train,y_train,batch_size = 32 ,epochs = 100)

Epoch 1/100
250/250 [==============================] - 4s 2ms/step - loss: 0.6214 - accuracy: 0.7074
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4982 - accuracy: 0.8021
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4604 - accuracy: 0.8119
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4426 - accuracy: 0.8174
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4316 - accuracy: 0.8179
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4239 - accuracy: 0.8189
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4178 - accuracy: 0.8225
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4126 - accuracy: 0.8249
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4081 - accuracy: 0.8255
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4047 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3302 - accuracy: 0.8633
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3304 - accuracy: 0.8643
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8649
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8624
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3303 - accuracy: 0.8627
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8629
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3297 - accuracy: 0.8635
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3296 - accuracy: 0.8635
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8649
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3300 - accuracy: 

3. Making the predictions

In [23]:
### Predicting a new results with following features
# 1.Geography = France
# 2.credit score = 600
# 3.Gender = Male
# 4.Age = 40 
# 5.Tenure = 3 years
# 6.Balance = $60000
# 7.Number of products = 2
# 8.Active member = yes
# 9.Customer with credit card = yes
# 10.Estimated salary = $50000
# he will exit or not??
res = bool(ann.predict(scaler.transform([[1.0,0.0,0.0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)
print(f"Prediction is : {res}")

Prediction is : False


4.Predicting the test results

In [32]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
np.c_[y_pred,y_test]

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [1, 1],
       [0, 1],
       [0, 0]], dtype=int64)

5. Confusion matrix

In [30]:
from sklearn.metrics import confusion_matrix,accuracy_score
matrix = confusion_matrix(y_test,y_pred)
matrix

array([[1562,   55],
       [ 226,  157]], dtype=int64)

6. Accuracy