### Importing the libraries

In [94]:
import numpy as np
import pandas as pd

### Data Preprocessing

### 1.Importing the datasets

In [141]:
data2 = pd.read_csv("breast_cancer.csv")

In [142]:
df = pd.DataFrame(data2)

In [143]:
df.Class.unique()

array([2, 4], dtype=int64)

In [144]:
X = data2.iloc[:,1:-1].values
y = data2.iloc[:,-1:].values

### Looking for any missing values

In [145]:
df.isnull()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0                 False            False                    False   
1                 False            False                    False   
2                 False            False                    False   
3                 False            False                    False   
4                 False            False                    False   
..                  ...              ...                      ...   
678               False            False                    False   
679               False            False                    False   
680               False            False                    False   
681               False            False                    False   
682               False            False                    False   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                       False              False                        False   
1                       False              False                        False   
2                       False              False                        False   
3                       False              False                        False   
4                       False              False                        False   
..                        ...                ...                          ...   
678                     False              False                        False   
679                     False              False                        False   
680                     False              False                        False   
681                     False              False                        False   
682                     False              False                        False   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0          False            False            False    False  False  
1          False            False            False    False  False  
2          False            False            False    False  False  
3          False            False            False    False  False  
4          False            False            False    False  False  
..           ...              ...              ...      ...    ...  
678        False            False            False    False  False  
679        False            False            False    False  False  
680        False            False            False    False  False  
681        False            False            False    False  False  
682        False            False            False    False  False  

[683 rows x 11 columns]

In [146]:
missing = df.isnull().sum()
print(missing)

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64


### Splitting the dataset into test and training set

In [147]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

### Training the model on Logistic regression

In [148]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

c:\python3.7\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

### Predicting the test results

In [173]:
y_pred = classifier.predict(X_test)
np.concatenate((y_test.reshape(y_test.size,1),y_pred.reshape(y_test.size,1)),1)

array([[2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [4, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2,

### Confusion matrix

In [174]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test,y_pred)
matrix

array([[90,  0],
       [ 2, 45]], dtype=int64)

### Computing the accuracy with K-FOLD cross validation

In [177]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier,X = X_train,y = y_train)
print("Acurracy : {:.2f}%".format(accuracies.mean()*100))
print("Standard Deviation : {:.2f}".format(accuracies.std()*100))

Acurracy : 96.16%
Standard Deviation : 1.77


c:\python3.7\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\python3.7\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\python3.7\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\python3.7\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\python3.7